CREATE DATABASE drivemecrazy;
USE drivemecrazy;

CREATE TABLE CUSTOMER (
    CUS_ID CHAR(7) NOT NULL PRIMARY KEY, 
    CUS_FIRST_NAME VARCHAR(50) NOT NULL,
    CUS_LAST_NAME VARCHAR(50) NOT NULL,
    CUS_EMAIL VARCHAR(100) NOT NULL,
    CUS_ADDRESS VARCHAR(255) NOT NULL,
    CUS_DRIVERS_LICENSE VARCHAR(13) NOT NULL,
    CUS_PHONE_NUMBER CHAR(11) NOT NULL,
    CUS_PASSWORD VARCHAR(255) NOT NULL
)  ENGINE=INNODB;

CREATE TABLE CAR (
    CAR_ID CHAR(7) NOT NULL PRIMARY KEY,
    CAR_PLATE_NUMBER VARCHAR(8) NOT NULL,
    CAR_MODEL VARCHAR(255) NOT NULL,
    CAR_SEAT_CAPACITY INT NOT NULL,
    CAR_COLOR VARCHAR(20) NOT NULL,
    CAR_FUEL_TYPE ENUM('Diesel', 'Petrol', 'Electric', 'Hybrid') NOT NULL,
    CAR_TRANSMISSION ENUM('Manual', 'Automatic') NOT NULL,
    CAR_PRICE DECIMAL(12 , 2 ) NOT NULL, -- DAILY RATE
    CAR_TYPE ENUM('Hatchback', 'Sedan', 'SUV', 'Pickup', 'Van', 'Sports') NOT NULL,
    CAR_STATUS ENUM('Available', 'Unavailable') NOT NULL,
    CAR_IMG LONGBLOB NOT NULL
)  ENGINE=INNODB;

CREATE TABLE BOOKING (
    BOOKING_ID CHAR(7) NOT NULL PRIMARY KEY,
    CUS_ID CHAR(7) NOT NULL,
    CAR_ID CHAR(7) NOT NULL,
    BOOKING_START_DATE DATE NOT NULL,
    BOOKING_END_DATE DATE NOT NULL,
    BOOKING_STATUS ENUM('Pending', 'Approved', 'Cancelled', 'Completed') NOT NULL,
    BOOKING_TOTAL_PRICE DECIMAL(12 , 2 ) NOT NULL,
    BOOKING_PAYMENT_STATUS ENUM('Unpaid','Partial', 'Paid') NOT NULL,
    FOREIGN KEY (CUS_ID)
        REFERENCES CUSTOMER (CUS_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (CAR_ID)
        REFERENCES CAR (CAR_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;

CREATE TABLE PAYMENT (
    PAYMENT_ID CHAR(7) NOT NULL PRIMARY KEY,
    CUS_ID CHAR(7) NOT NULL,
    BOOKING_ID CHAR(7) NOT NULL,
    PAYMENT_AMOUNT DECIMAL(12,2) NOT NULL,				
    FOREIGN KEY (CUS_ID)
        REFERENCES CUSTOMER (CUS_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (BOOKING_ID)
        REFERENCES BOOKING (BOOKING_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;
    
CREATE TABLE ADMIN (
    ADMIN_ID CHAR(7) NOT NULL PRIMARY KEY,
    ADMIN_EMAIL VARCHAR(100) NOT NULL,
    ADMIN_PASSWORD VARCHAR(100) NOT NULL,
    ADMIN_PHONE CHAR(11) NOT NULL
)  ENGINE=INNODB;

ALTER TABLE BOOKING ADD ADMIN_ID CHAR(7) NULL;
ALTER TABLE BOOKING ADD FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ADMIN_ID);

INSERT INTO ADMIN VALUES
('ADM0001', 'admin1@dmc.com', 'adminpass1', '09170000001'),
('ADM0002', 'admin2@dmc.com', 'adminpass2', '09170000002'),
('ADM0003', 'admin3@dmc.com', 'adminpass3', '09170000003');

select * from admin; 
select * from customer; 
select * from booking; 
select * from car; 